= AWS Compute Options

This repo contains a simple application that consists of three microservices. The sample application uses three services:

. "`webapp`": Web application microservice uses "`greeting`" and "`name`"" microservice to generate a greeting for a person.
. "`greeting`": A microservice that returns a greeting.
. "`name`": A microservice that returns a person’s name based upon `{id}` in the URL.

Each application is deployed using the following AWS Compute options:

. EC2
. Beanstalk
. Containers
.. Docker EE
.. Kubernetes
... BYO K8s cluster
... Amazon EKS
.. Amazon ECS
... AWS Fargate
. Serverless
.. AWS Lambda
.. SAM Local

Each deployment model will highlight:

. Local dev, test and debug
. How service discovery is used
. Remote debugging
. Monitoring using X-Ray

== Services

Change to the "`services`" directory: `cd services`

=== Run application

. In Terminal 1: `mvn -pl greeting wildfly-swarm:run`
. In Terminal 2: `mvn -pl name wildfly-swarm:run`
. In Terminal 3: `mvn -pl webapp wildfly-swarm:run`
. In Terminal 4: `curl http://localhost:8080/`

=== Run/test individual services

==== Greeting service

. Run the service: `mvn -pl greeting wildfly-swarm:run`
. Test the service: `curl http://localhost:8081/resources/greeting`
. Create Docker image: `mvn -pl greeting package -Pdocker`

==== Name service

. Run the service: `mvn -pl name wildfly-swarm:run`
. Test the service
.. `curl http://localhost:8082/resources/names`
.. `curl http://localhost:8082/resources/names/1`
. Create Docker image: `mvn -pl name package -Pdocker`

==== Webapp service

. Run the service: `mvn -pl webapp wildfly-swarm:run`
. Test the service: `curl http://localhost:8080/`
. Create Docker image: `mvn -pl webapp package -Pdocker`

=== Docker images

. *Docker image name*: By default, the Docker image name is `arungupta/<service>` where `<service>` is `greeting`, `name` or `webapp`. Create the image in your repo as: `mvn -pl <service> package -Pdocker -Ddocker.repo=<repo>`
. *Push Docker images to repo*:
+
```
docker push <repo>/greeting
docker push <repo>/name
docker push <repo>/webapp

```
+
This is a workaround until https://github.com/aws-samples/aws-compute-options/issues/4 is fixed.

=== Helm charts

Make sure `kubectl` CLI and is configured for the Kubernetes cluster. Also, make sure Helm is installed on that Kubernetes cluster.

. Create Helm charts: `helm install --name myapp app-helm`
. Delete Helm charts: `helm delete --purge myapp`

Accessing the application will not work because of https://github.com/aws-samples/aws-compute-options/issues/6.

== License

This library is licensed under the Amazon Software License.

