= AWS Compute Options

This repo contains a simple application that consists of three microservices. The sample application uses three services:

. "`webapp`": Web application microservice uses "`greeting`" and "`name`"" microservice to generate a greeting for a person.
. "`greeting`": A microservice that returns a greeting.
. "`name`": A microservice that returns a person’s name based upon `{id}` in the URL.

Each application is deployed using the following AWS Compute options:

. Containers
.. Docker EE
.. Kubernetes
... BYO K8s cluster
... Amazon EKS
.. Amazon ECS
... EC2
... Fargate
. Serverless
.. AWS Lambda & Amazon API Gateway
.. SAM Local

Each deployment model will highlight:

. Local dev, test and debug
. Remote debugging
. Service discovery
. Monitoring (possibly using X-Ray)
. Deployment pipeline

== Build and Test Services

Change to the "`services`" directory: `cd services`
. Compile all projects. In Terminal 1: `mvn clean package`

Testing war services in local
. Change directory to the "`services/war`": `cd services/war`
. Greeting service in Terminal 1: `mvn -pl greeting wildfly-swarm:run -DskipTests`
.. Optionally test: `curl http://localhost:8081/resources/greeting`
. Name service in Terminal 2: `mvn -pl name wildfly-swarm:run`
.. Optionally test:
... `curl http://localhost:8082/resources/names`
... `curl http://localhost:8082/resources/names/1`
. Webapp service in Terminal 3: `mvn -pl webapp wildfly-swarm:run`
. Invoke the application in Terminal 4: `curl http://localhost:8080/`

== Build and Push Docker images
. *From the "`services/war`" directory
. *Create Docker image*: `mvn -pl <service> package -Pdocker -DskipTests` where `<service>` is `greeting`, `name` or `webapp`
. *Docker image name*: By default, the Docker image name is `arungupta/<service>`. Create the image in your repo as: `mvn -pl <service> package -Pdocker -Ddocker.repo=<repo>`
. *Push Docker images to registry*:
+
```
docker push <repo>/greeting-war
docker push <repo>/name-war
docker push <repo>/webapp-war

```
+
This is a workaround until https://github.com/aws-samples/aws-compute-options/issues/4 is fixed.

== Deploy Application to Kubernetes with Helm

Make sure `kubectl` CLI is installed and configured for the Kubernetes cluster. Also, make sure Helm is installed on that Kubernetes cluster.

. Install Helm CLI: `brew install kubernetes-helm`
. Install Helm in Kubernetes cluster: `helm init`
. Create Helm chart: `helm install --name myapp apps/k8s/helm/myapp`
. Access the application: `curl http://$(kubectl get svc/myapp-webapp -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')`
. Delete Helm chart: `helm delete --purge myapp`

== Deploy Application to Kubernetes with Standalone Manifests

Make sure `kubectl` CLI is installed and configured for the Kubernetes cluster.

. Apply the manifests: `kubectl apply -f apps/k8s/standalone/manifest.yml`
. Access the application: `curl http://$(kubectl get svc/webapp -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')`
. Delete the application: `kubectl delete -f apps/k8s/standalone/manifest.yml`

== Deploy Application to Amazon ECS

== Deploy Application to AWS Lambda

For local testing and deploying to AWS Lambda and Amazon API Gateway refer to the README file in the link:apps/lambda[`apps/lambda` folder].

== Deploy Application to Docker Swarm

. `docker swarm init`
. `cd apps/docker`
. `docker stack deploy --compose-file docker-compose.yaml myapp`
. Access the application: `curl http://localhost:80`
.. Optionally test the endpoints:
... Greeting endpoint: `curl http://localhost:8081/resources/greeting`
... Name endpoint: `curl http://localhost:8082/resources/names/1`
. Remove the stack: `docker stack rm myapp`

=== Debug

. List stack:
+
```
$ docker stack ls
NAME                SERVICES
myapp               3
```
+
. List services in the stack:
+
```
$ docker stack services myapp
ID                  NAME                     MODE                REPLICAS            IMAGE                       PORTS
8hv33y3ry5la        myapp_greeting-service   replicated          1/1                 arungupta/greeting-war:latest   *:8081->8080/tcp
kyup1v84cv7q        myapp_name-service       replicated          1/1                 arungupta/name-war:latest       *:8082->8080/tcp
wcjhglfym28g        myapp_webapp-service     replicated          1/1                 arungupta/webapp-war:latest     *:80->8080/tcp
```
+
. List containers:
+
```
$ docker container ls -f name=myapp*
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                          NAMES
7cd2ec331b2a        arungupta/webapp-war:latest     "/deployments/run-ja…"   20 seconds ago      Up 20 seconds       8080/tcp, 8778/tcp, 9779/tcp   myapp_webapp-service.1.fvr9sae08ieu08lf8agfz2mwy
8436c6cc3110        arungupta/greeting-war:latest   "/deployments/run-ja…"   20 seconds ago      Up 18 seconds       8080/tcp, 8778/tcp, 9779/tcp   myapp_greeting-service.1.64idmwjlcvacniix6ll1egeoa
3a0a951f0a2d        arungupta/name-war:latest       "/deployments/run-ja…"   20 seconds ago      Up 20 seconds       8080/tcp, 8778/tcp, 9779/tcp   myapp_name-service.1.o7byxuzrc5vbfoyye8kuo19ws
```
+
. Get logs for all the containers in the `webapp` service:
+
```
$ docker service logs myapp_webapp-service
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | exec java -cp . -jar /deployments/webapp-swarm.jar
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:00,460 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:2018.2.0
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:00,514 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                  Elytron - STABLE          org.wildfly.swarm:elytron:2018.2.0
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:00,515 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                   JAX-RS - STABLE          org.wildfly.swarm:jaxrs:2018.2.0
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:00,516 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:2018.2.0
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:05,777 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:06,078 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0049: WildFly Swarm 2018.2.0 (WildFly Core 3.0.8.Final) starting

. . .

org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0027: Starting deployment of "webapp.war" (runtime-name: "webapp.war")
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:11,384 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0018: Host default-host starting
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:11,878 INFO  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 10) RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.wildfly.swarm.generated.WildFlySwarmDefaultJAXRSApplication
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:11,909 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 10) WFLYUT0021: Registered web context: '/' for server 'default-server'
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:11,984 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "webapp.war" (runtime-name : "webapp.war")
myapp_webapp-service.1.gb56vv5mw6u7@linuxkit-025000000001    | 2018-02-16 03:07:12,004 INFO  [org.wildfly.swarm] (main) WFSWARM99999: WildFly Swarm is Ready
```

== License

This library is licensed under the Amazon Software License.

